### ISSUE TITLE
onNewRequest doesn't send a notification

### ISSUE THREAD

**Issue by ornelasf1** [markbeep/AudioBookRequest#99]
Notification `onNewRequest` doesn't send a notification

My notification URL setup:
![Image](https://github.com/user-attachments/assets/3cd690f6-75bf-4321-ac07-33b48bddea34)

Clicking the testing button sends a successful notification to Apprise but on the event it doesn't work.

Successful test notification on Apprise from Audiobookrequest
```
172.18.0.13 - - [20/Apr/2025:20:49:16 +0000] "POST /notify/f01427185829be0f3e78eb81bf940e08ac8c3c0f4abbbdd1bba67288972f96f9 HTTP/1.1" 200 189 "-" "Python/3.12 aiohttp/3.11.13"
2025/04/20 20:49:16 [info] 43#43: *67 client 172.18.0.13 closed keepalive connection
```

**Comment by markbeep** [comment]
Hey, could you try to request some book, wait about 10 seconds to let it try to send a notification, and then send like the last 50 lines of the logs here? That might help me figure out what's going on.

**Comment by ornelasf1** [comment]
Sure, the highlight is my audiobook request. Not much happens after that

![Image](https://github.com/user-attachments/assets/3e0eca56-e237-4ef7-ac7b-6bfdeba882c2)

this is my docker compose file
```
audiobookrequest:
    image: markbeep/audiobookrequest:1
    container_name: audiobookrequest
    ports:
      - "8877:8000"
    volumes:
      - ./data/audiobookrequest/config:/config
    environment:
      - ABR_APP__LOG_LEVEL=DEBUG
      - ABR_APP__OPENAPI_ENABLED=true
    restart: unless-stopped
```
